server:
  port: 8888

spring:
  # 默认值为 classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/
  resources:
    static-locations: classpath:/static/ #这里设置要指向的路径，多个使用英文逗号隔开，在前面的优先级高


  thymeleaf:
          prefix: classpath:/templates/
          mode: HTML
          cache: false
          encoding: UTF-8
            #     新版本不支持content-type: text/html，故新写法
          servlet:
              content-type: text/html
          suffix: .html

  datasource:
    name: news_website
    url: jdbc:mysql://localhost:3306/news_website?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone = GMT%2B8
    username: root
    password: 312ybj

  mail:
    host: smtp.qq.com
    username: 1793870688@qq.com
    password: auuderulnsaqdcia

  cache:
    jcache:
     config: classpath:/static/ehcache.xml


  logging:
    level:
      com:
        looedu:
          mapper: debug
  redis:
    host: 127.0.0.1
    port: 6379
    database: 1
    password:
    # 连接池最大连接数（使用负值表示没有限制）
    spring.redis.jedis.pool.max-active: 8
    # 连接池最大阻塞等待时间（使用负值表示没有限制）
    spring.redis.jedis.pool.max-wait: -1
    # 连接池中的最大空闲连接
    spring.redis.jedis.pool.max-idle: 8
    # 连接池中的最小空闲连接
    spring.redis.jedis.pool.min-idle: 0
    # 连接超时时间（毫秒）
    spring.redis.timeout: 5000



